/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdimagenes.view;

import java.util.Dictionary;
import java.util.Hashtable;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author daniel
 */
public class BrilloPanel extends javax.swing.JPanel {

    private JSlider jSlider1;
    private JLabel jLabel1;
    
    /**
     * Creates new form BrilloPanel
     */
    public BrilloPanel() {
        //initComponents();
        init();
    }
    
    public double getSliderValue() {
        return jSlider1.getValue();
    }

    private void init() {

        jLabel1 = new JLabel();
        jLabel1.setText("Factor Brillo -> 10");

        jSlider1 = new JSlider(5, 35, 10);
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setPaintTicks(true);
        Dictionary<Integer, JLabel> labelTable = new Hashtable<>();
        labelTable.put(35, new JLabel("35"));
        labelTable.put(30, new JLabel("30"));
        labelTable.put(25, new JLabel("25"));
        labelTable.put(20, new JLabel("20"));
        labelTable.put(15, new JLabel("15"));
        labelTable.put(10, new JLabel("10"));
        labelTable.put(5, new JLabel("5"));
        jSlider1.setLabelTable(labelTable);
        jSlider1.setPaintLabels(true);

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
            public void stateChanged(javax.swing.event.ChangeEvent ce) {
                double value = jSlider1.getValue();
                jLabel1.setText("Factor Brillo -> " + value);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)
                        .addContainerGap(128, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
