/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdimagenes.view;

import java.util.Dictionary;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author daniel
 */
public class CorreccionGamaPanel extends javax.swing.JPanel {

    private JSlider jSlider1;
    private JLabel jLabel1;

    /**
     * Creates new form CorreccionGamaPanel
     */
    public CorreccionGamaPanel() {
        //initComponents();
        init();
    }

    public double getSliderValue() {
        double value = jSlider1.getValue() <= 100 ? (jSlider1.getValue() / 100.0) : ((jSlider1.getValue() - 100) / 10) + 1;
        return value;
    }

    private void init() {

        jLabel1 = new JLabel();
        jLabel1.setText("Factor Gamma -> 1");

        jSlider1 = new JSlider(0, 190, 100);
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setPaintTicks(true);
        Dictionary<Integer, JLabel> labelTable = new Hashtable<>();
        labelTable.put(190, new JLabel("10"));
        labelTable.put(180, new JLabel("9"));
        labelTable.put(170, new JLabel("8"));
        labelTable.put(160, new JLabel("7"));
        labelTable.put(150, new JLabel("6"));
        labelTable.put(140, new JLabel("5"));
        labelTable.put(130, new JLabel("4"));
        labelTable.put(120, new JLabel("3"));
        labelTable.put(110, new JLabel("2"));
        labelTable.put(100, new JLabel("1"));
        labelTable.put(90, new JLabel(".9"));
        labelTable.put(80, new JLabel(".8"));
        labelTable.put(70, new JLabel(".7"));
        labelTable.put(60, new JLabel(".6"));
        labelTable.put(50, new JLabel(".5"));
        labelTable.put(40, new JLabel(".4"));
        labelTable.put(30, new JLabel(".3"));
        labelTable.put(20, new JLabel(".2"));
        labelTable.put(10, new JLabel(".1"));
        labelTable.put(0, new JLabel("0"));
        jSlider1.setLabelTable(labelTable);
        jSlider1.setPaintLabels(true);

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent ce) {
                double value = jSlider1.getValue() <= 100 ? (jSlider1.getValue() / 100.0) : ((jSlider1.getValue() - 100.0) / 10.0) + 1;
                jLabel1.setText("Factor Gamma -> " + value);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)
                        .addContainerGap(128, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
