/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdimagenes.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Dictionary;
import java.util.Hashtable;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.apache.commons.io.FilenameUtils;
import pdimagenes.enums.Canal;
import pdimagenes.herramientas.FiltroGris;
import pdimagenes.herramientas.Histograma;
import pdimagenes.herramientas.OperacionPunto;

/**
 *
 * @author USUARIO
 */
public class EspecificacionHistogramaFrame extends javax.swing.JFrame {

    private final ImagenesFrame imagenesFrame;
    private BufferedImage image;
    private BufferedImage imagenModificada;
    private Histograma histogramaModificada;
    private OperacionPunto operacionPunto;

    /**
     * Creates new form EspecificacionHistogramaFrame
     */
    public EspecificacionHistogramaFrame(ImagenesFrame imagenesFrame) {
        initComponents();
        this.imagenesFrame = imagenesFrame;
        this.image = imagenesFrame.getImage();
        operacionPunto = new OperacionPunto();
        init();;
    }

    private void init() {

        //Meter la imagen en el jlabel
        image = new FiltroGris().grisPromedio(image);
        HistogramaVisual visual = new HistogramaVisual(image);
        Histograma histograma = new Histograma(image);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(visual.getHistograma(Canal.R, Color.GRAY, "GRAY"), BorderLayout.CENTER);
        jPanel1.repaint();
        jLabel1.setIcon(new ImageIcon(image.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
        jPanel3.removeAll();
        jPanel3.revalidate();
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(visual.getHistograma(histograma.obtenerHistogramaAcumulativoGrises(255), Color.GRAY, "GRAY"), BorderLayout.CENTER);
        jPanel3.repaint();

        //Preparar el slider
        jSlider1.setMaximum(9);
        jSlider1.setMinimum(2);
        jSlider1.setValue(5);
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setPaintTicks(true);
        Dictionary<Integer, JLabel> labelTable = new Hashtable<>();
        labelTable.put(9, new JLabel("9"));
        labelTable.put(8, new JLabel("8"));
        labelTable.put(7, new JLabel("7"));
        labelTable.put(6, new JLabel("6"));
        labelTable.put(5, new JLabel("5"));
        labelTable.put(4, new JLabel("4"));
        labelTable.put(3, new JLabel("3"));
        labelTable.put(2, new JLabel("2"));
        jSlider1.setLabelTable(labelTable);
        jSlider1.setPaintLabels(true);

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent ce) {
                double value = jSlider1.getValue();
                jLabel2.setText("Puntos: " + value);
            }
        });

    }

    public void setImage() {

        histogramaModificada = new Histograma(imagenModificada);
        jPanel5.removeAll();
        jPanel5.revalidate();
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(new HistogramaVisual(imagenModificada).getHistograma(histogramaModificada.obtenerHistogramaAcumulativoGrises(255), Color.GRAY, "GRAY"), BorderLayout.CENTER);
        jPanel5.repaint();
        jLabel3.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane2.getWidth(), jScrollPane2.getHeight(), java.awt.Image.SCALE_SMOOTH)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Especificación de Histograma");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 350, 230));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 360, 260));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen Modificada"));
        jScrollPane2.setViewportView(jLabel3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 390, 300));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen Original"));
        jScrollPane1.setViewportView(jLabel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 290));
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 530, -1));

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, -1, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 340, 230));

        jLabel2.setText("Puntos: 5");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, 20));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Tomamos valor de slider y aplicamos algoritmo
        imagenModificada = operacionPunto.especHistogramaInterpolacion(image, jSlider1.getValue());
        setImage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int action = jFileChooser1.showSaveDialog(null);
            if (action != JFileChooser.APPROVE_OPTION) {
                return;
            }
            File file = jFileChooser1.getSelectedFile();
            ImageIO.write(imagenModificada, FilenameUtils.getExtension(file.getName()), file);
            JOptionPane.showMessageDialog(this, "Imagen guardada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
