/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdimagenes.view;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import pdimagenes.herramientas.FiltroGris;
import pdimagenes.herramientas.FiltrosRegionales;

/**
 *
 * @author USUARIO
 */
public class FiltrosRegionalesFrame extends javax.swing.JFrame {

    private final ImagenesFrame imagenesFrame;
    private BufferedImage imagen;
    private BufferedImage imagenModificada;
    
    /**
     * Creates new form FiltrosRegionalesFrame
     */
    public FiltrosRegionalesFrame(ImagenesFrame imagenesFrame) {
        this.imagenesFrame = imagenesFrame;
        this.imagen = imagenesFrame.getImage();
        initComponents();
        init();
    }
    
    private void init() {
        jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtros Regionales");

        jScrollPane1.setViewportView(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laplaciano", "Laplaciano Rotado", "Laplaciano Mixto", "Sobel", "Canny" }));

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox1.getSelectedItem() instanceof String) {
            String operacion = (String) jComboBox1.getSelectedItem();
            switch (operacion) {
                case "Laplaciano" : {
                    imagenModificada = new FiltrosRegionales().laplacianoGrises(new FiltroGris().grisPromedio(imagen), FiltrosRegionales.MATRIZ_CONVU_LAPLACIANO);
                    jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Laplaciano Rotado" : {
                    imagenModificada = new FiltrosRegionales().laplacianoGrises(new FiltroGris().grisPromedio(imagen), FiltrosRegionales.MATRIZ_CONVU_LAPLACIANO_ROT);
                    jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Laplaciano Mixto" : {
                    imagenModificada = new FiltrosRegionales().laplacianoGrises(new FiltroGris().grisPromedio(imagen), FiltrosRegionales.MATRIZ_CONVU_LAPLACIANO_MIXTA);
                    jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Sobel" : {
                    imagenModificada = new FiltrosRegionales().sobelGrises(new FiltroGris().grisPromedio(imagen));
                    jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Canny" : {
                    imagenModificada = new FiltrosRegionales().cannyGrises(imagen);
                    jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
