/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdimagenes.view;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import pdimagenes.herramientas.FiltroGris;
import pdimagenes.herramientas.FiltrosRegionales;

/**
 *
 * @author USUARIO
 */
public class FiltrosSuavizadoFrame extends javax.swing.JFrame {

    private final ImagenesFrame imagenesFrame;
    private BufferedImage imagen;
    private BufferedImage imagenModificada;
    
    /**
     * Creates new form FiltrosSuavizadoFrame
     */
    public FiltrosSuavizadoFrame(ImagenesFrame imagenesFrame) {
        this.imagenesFrame = imagenesFrame;
        this.imagen = new FiltroGris().grisPromedio(imagenesFrame.getImage());
        initComponents();
        init();
    }
    
    private void init() {
        jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtros Suavizado");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Media Direccional", "Media Ponderada", "Media Gaussiana Fuerte", "Media Gaussiana Débil", "Media Armónica", "Mediana", "Mediana Recortada" }));

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox1.getSelectedItem() instanceof String) {
            String operacion = (String) jComboBox1.getSelectedItem();
            switch (operacion) {
                case "Media" : {
                    imagen = new FiltrosRegionales().media(imagen);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Media Direccional" : {
                    imagen = new FiltrosRegionales().mediaDireccional(imagen);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Media Ponderada" : {
                    imagen = new FiltrosRegionales().mediaPonderada(imagen);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Media Gaussiana Fuerte" : {
                    imagen = new FiltrosRegionales().mediaGaussiana(imagen, FiltrosRegionales.MATRIZ_CONVU_GAUSS_FUERTE,true);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Media Gaussiana Débil" : {
                    imagen = new FiltrosRegionales().mediaGaussiana(imagen, FiltrosRegionales.MATRIZ_CONVU_GAUSS_DEBIL,false);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Media Armónica" : {
                    imagen = new FiltrosRegionales().mediaArmonica(imagen);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Mediana" : {
                    imagen = new FiltrosRegionales().mediana(imagen);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
                case "Mediana Recortada" : {
                    imagen = new FiltrosRegionales().medianaRecortada(imagen, 3, 1);
                    jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
