/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdimagenes.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import pdimagenes.enums.Canal;
import pdimagenes.parciales.PrimerParcial;

/**
 *
 * @author daniel
 */
public class PrimerParcialFrame extends javax.swing.JFrame {

    private BufferedImage imagen;
    private PrimerParcial primerParcial;
    
    /**
     * Creates new form PrimerParcialFrame
     */
    public PrimerParcialFrame(BufferedImage imagen) {
        initComponents();
        this.imagen = imagen;
        init();
    }

    private void init() {
        
        primerParcial = new PrimerParcial();
        
        jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Primer Parcial");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jLabel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 460));

        jButton1.setText("Primera Etapa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        jButton2.setText("Segunda Etapa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 310, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imagen = primerParcial.primerEtapa(imagen);
        jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //BufferedImage img = primerParcial.segundaEtapa(imagen);
        imagen = primerParcial.segundaEtapa(imagen);
        HistogramaVisual visual = new HistogramaVisual(imagen);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(visual.getHistograma(primerParcial.getUltimoHistograma().getRed(), Color.RED, "RED"), BorderLayout.CENTER);
        jPanel1.repaint();
        //jLabel1.setIcon(new ImageIcon(img.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
        jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
