/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdimagenes.view;

import java.awt.image.BufferedImage;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import pdimagenes.herramientas.FiltroGris;
import pdimagenes.herramientas.Relieves;

/**
 *
 * @author USUARIO
 */
public class RelievesFrame extends javax.swing.JFrame {

    private final ImagenesFrame imagenesFrame;
    private BufferedImage imagen;
    private BufferedImage imagenModificada;

    /**
     * Creates new form RelievesFrame
     */
    public RelievesFrame(ImagenesFrame imagenesFrame) {
        this.imagenesFrame = imagenesFrame;
        this.imagen = new FiltroGris().grisPromedio(imagenesFrame.getImage());
        initComponents();
        init();
    }

    private void init() {
        jLabel1.setIcon(new ImageIcon(imagen.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtros Relieve");

        jScrollPane1.setViewportView(jLabel1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("45°");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("0°");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer Orden", "Segundo Orden", " " }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("90°");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("135°");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("180°");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("225°");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("270°");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("315°");

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButton4)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton7)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton6))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jSeparator1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox1.getSelectedItem() instanceof String) {
            //Obtenemos angulo
            String angulo = "";
            Enumeration<AbstractButton> buttons = buttonGroup1.getElements();
            while (buttons.hasMoreElements()) {
                JRadioButton rb = (JRadioButton) buttons.nextElement();
                if (rb.isSelected()) {
                    angulo = rb.getText();
                    break;
                }
            }
            //Obtenemos orden
            String orden = (String) jComboBox1.getSelectedItem();
            if (orden.equals("Primer Orden")) {
                switch (angulo) {
                    case "0°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_0, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "45°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_45, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "90°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_90, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "135°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_135, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "180°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_180, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "225°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_225, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "270°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_270, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "315°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_1ER_ORDEN_315, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                }
            } else if (orden.equals("Segundo Orden")) {
                switch (angulo) {
                    case "0°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_0, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "45°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_45, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "90°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_90, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "135°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_135, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "180°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_180, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "225°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_225, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "270°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_270, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                    case "315°": {
                        imagenModificada = new Relieves().aplicarRelieve(imagen, Relieves.MATRIZ_CONVU_2DO_ORDEN_315, 256);
                        jLabel1.setIcon(new ImageIcon(imagenModificada.getScaledInstance(jScrollPane1.getWidth(), jScrollPane1.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                        break;
                    }
                }
            } else {
                System.out.println("Orden desconocido");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
